//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1100 with alias "slider"
	/// <summary>Slider</summary>
	public partial interface ISlider : IPublishedContent
	{
		/// <summary>Slides</summary>
		IEnumerable<IPublishedContent> Slides { get; }
	}

	/// <summary>Slider</summary>
	[PublishedContentModel("slider")]
	public partial class Slider : PublishedContentModel, ISlider
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "slider";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Slider(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Slider, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Slides: Add multiple slides to be shown in the slider.
		///</summary>
		[ImplementPropertyType("slides")]
		public IEnumerable<IPublishedContent> Slides
		{
			get { return GetSlides(this); }
		}

		/// <summary>Static getter for Slides</summary>
		public static IEnumerable<IPublishedContent> GetSlides(ISlider that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("slides"); }
	}
}
